(deftheme aboltination-v2
  "Created 2024-02-03.")

(custom-theme-set-faces
 'aboltination-v2
 '(cursor ((t (:background "dark magenta" :distant-foreground "gainsboro" :foreground "gainsboro"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#9cd1bb"))))
 '(homoglyph ((t (:foreground "magenta"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(highlight ((t (:background "dark magenta" :foreground "gainsboro"))))
 '(region ((t (:extend t :background "#3a3d4b"))))
 '(shadow ((t (:foreground "#595d68"))))
 '(secondary-selection ((t (:extend t :background "#535763"))))
 '(trailing-whitespace ((t (:background "cornflower blue"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:extend t :foreground "#c39ac9" :inherit (italic)))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#696d77"))))
 '(font-lock-constant-face ((t (:foreground "#c39ac9"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#8e9199" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-constant-face))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:weight semi-bold :foreground "#bad761"))))
 '(font-lock-keyword-face ((t (:foreground "#9cd1bb"))))
 '(font-lock-negation-char-face ((t (:foreground "#ff657a" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#c39ac9"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#ff657a" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#ff657a" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#ff657a" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "medium spring green"))))
 '(font-lock-type-face ((t (:foreground "#9cd1bb" :inherit (default)))))
 '(font-lock-variable-name-face ((t (:foreground "cyan"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:inherit warning :foreground "#5b4343"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#ffd76d"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#535763" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#eaf2f1" :background "#1E1F2B"))))
 '(mode-line ((t (:box nil :foreground "#eaf2f1" :background "#3a3d4b"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#ffd76d"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#eaf2f1" :background "#282a3a"))))
 '(isearch ((t (:weight bold :box (:line-width (2 . 2) :color "#ffd76d" :style nil) :inherit (match)))))
 '(isearch-fail ((t (:weight bold :foreground "#ff657a" :background "#955f5f"))))
 '(lazy-highlight ((t (:weight bold :foreground "#4c5361" :background "#e8e4ff" :inherit (match)))))
 '(match ((t (:weight bold :foreground "#eaf2f1" :background "#3a3d4b"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1f1e24" :foreground "gainsboro" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 103 :width normal :foundry "ADBO" :family "Source Code Pro")))))

(provide-theme 'aboltination-v2)
